# This is a basic workflow to help you get started with Actions
name: Blue-Green-strategy

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 

  setupminikube:
  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Set up minikube on the Github Runner
      
      - name: start minikube
        id: minikube
        uses: medyagh/setup-minikube@master
      
      # Check if cluster is up and running
      - name: Get list of pods
        run: kubectl get pods -A
     
  deployapp:
  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      # Runs a set of commands using the runners shell
      - name: Deploy to Prod - GREEN
        uses: azure/k8s-deploy@v1.3
        with:
          namespace: default
          manifests: |
            ./kubernetes/service.yaml
            ./kubernetes/green-deploy.yaml
          images: |
            demogaurav.azurecr.io/green-nginx:1
          strategy: blue-green
          traffic-split-method: pod
          action: deploy  #deploy is the default; we will later use this to promote/reject


     # Check the pods
       # Check if cluster is up and running
      - name: Check pods in Prod - GREEN
        run: kubectl get pods -A
        
  approveapp:
    runs-on: ubuntu-latest
    needs: deployapp
    steps:
      - run: echo 'approve?'

  promotereject:
  
    runs-on: ubuntu-latest
    needs: approveapp
    
    steps:
      - uses: actions/checkout@v2
    

      - name: Promote App
        uses: azure/k8s-deploy@v1.3
        # Check if earlier step was successfull
        if: ${{ success() }}
        with:
          namespace: default
          manifests: |
            ./kubernetes/service.yaml
            ./kubernetes/deploy.yaml
          images: |
            demogaurav.azurecr.io/green-nginx:1
          strategy: blue-green
          traffic-split-method: pod
          action: promote  #deploy is the default; we will later use this to promote/reject

      
       # Check the pods
      - name: Pods post Promote (APPROVE) - GREEN
        run: kubectl get pods -A
        
        
      - name: Reject App
        uses: azure/k8s-deploy@v1.3
        if: ${{ failure() }}
        with:
          namespace: default
          manifests: |
            ./kubernetes/service.yaml
            ./kubernetes/deploy.yaml
          images: |
            demogaurav.azurecr.io/blue-nginx:1
          strategy: blue-green
          traffic-split-method: pod
          action: reject  #deploy is the default; we will later use this to promote/reject
          
          
        # Check the pods
      - name: Pods post Reject (REJECT) - BLUE
        run: kubectl get pods -A
